name: 'CI: ESLint, Prettier'

on:
  - pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM dependencies
        run: yarn install

      - name: Check ESLint
        run: yarn lint

      - name: Check Prettier
        run: yarn prettier:check
